[package]
name = "temp_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }

[features]
default = []
std = ["serde/std"]
